# Generated by Django 4.1.6 on 2023-02-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='F_text',
            field=models.TextField(default='default'),
        ),
    ]
